version: "2"

services:
    app:
        build: ./app
        container_name: "flask_app"
    notebooks:
        build: ./notebooks
        container_name: "jupyter_notebook"
        restart: always
        links:
            - db
        volumes:
            - ./data:/home/jovyan/work
        ports:
            - 8003:8888
    rest:
        build: ./api
        container_name: "rest_api"
        command: ["python", "api/rest.py"]
    db:
        build: ./db
        container_name: postgres_db
        ports:
            - 5432:3306
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_DB: "${POSTGRES_DB}"
        volumes:
            - ./data/:/home
        volumes_from:
            - postgresdata
